"""initial schema

Revision ID: 9cfe75a3d014
Revises: 
Create Date: 2026-09-12 08:32:23.099551
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '9cfe75a3d014'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # gen_random_uuid() is core in PG13+, but pgcrypto keeps older servers working.
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_stages',
    sa.Column('business_stage_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('business_stage_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_business_stages_slug'), 'business_stages', ['slug'], unique=True)
    op.create_table('challenges',
    sa.Column('challenge_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('challenge_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_challenges_slug'), 'challenges', ['slug'], unique=True)
    op.create_table('goals',
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('goal_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_goals_slug'), 'goals', ['slug'], unique=True)
    op.create_table('industries',
    sa.Column('industry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('industry_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_industries_slug'), 'industries', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('business_profiles',
    sa.Column('business_profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('industry_other', sa.String(length=150), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.industry_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_profile_id')
    )
    op.create_index(op.f('ix_business_profiles_user_id'), 'business_profiles', ['user_id'], unique=False)
    op.create_table('case_studies',
    sa.Column('case_study_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('industry_label', sa.String(length=150), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('client_type', sa.Text(), nullable=True),
    sa.Column('user_type', sa.Text(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('value_proposition', sa.Text(), nullable=True),
    sa.Column('revenue_model', sa.Text(), nullable=True),
    sa.Column('key_insight', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.industry_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('case_study_id')
    )
    op.create_index('idx_case_studies_published', 'case_studies', ['is_published'], unique=False)
    op.create_index(op.f('ix_case_studies_slug'), 'case_studies', ['slug'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('refresh_token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('refresh_token_id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('audit_submissions',
    sa.Column('audit_submission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('business_stage_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('client_description', sa.Text(), nullable=True),
    sa.Column('user_description', sa.Text(), nullable=True),
    sa.Column('problem_description', sa.Text(), nullable=True),
    sa.Column('value_creation_description', sa.Text(), nullable=True),
    sa.Column('revenue_model_description', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','submitted','analyzing','analyzed','failed')", name='chk_audit_submissions_status'),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.business_profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_stage_id'], ['business_stages.business_stage_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.goal_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('audit_submission_id')
    )
    op.create_index('idx_audit_submissions_business_profile_id', 'audit_submissions', ['business_profile_id'], unique=False)
    op.create_index('idx_audit_submissions_status', 'audit_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_audit_submissions_public_id'), 'audit_submissions', ['public_id'], unique=True)
    op.create_table('analysis_jobs',
    sa.Column('analysis_job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('audit_submission_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','succeeded','failed')", name='chk_analysis_jobs_status'),
    sa.ForeignKeyConstraint(['audit_submission_id'], ['audit_submissions.audit_submission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_job_id')
    )
    op.create_index('idx_analysis_jobs_status_created', 'analysis_jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_audit_submission_id'), 'analysis_jobs', ['audit_submission_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_public_id'), 'analysis_jobs', ['public_id'], unique=True)
    op.create_table('audit_challenges',
    sa.Column('audit_submission_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_submission_id'], ['audit_submissions.audit_submission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.challenge_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('audit_submission_id', 'challenge_id')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_submission_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('visual_score', sa.Integer(), nullable=False),
    sa.Column('technical_score', sa.Integer(), nullable=False),
    sa.Column('business_score', sa.Integer(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('analysis_duration_ms', sa.Integer(), nullable=True),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('overall_score BETWEEN 0 AND 100', name='chk_reports_overall_score'),
    sa.ForeignKeyConstraint(['audit_submission_id'], ['audit_submissions.audit_submission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_reports_audit_submission_id'), 'reports', ['audit_submission_id'], unique=True)
    op.create_table('site_snapshots',
    sa.Column('site_snapshot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_submission_id', sa.Integer(), nullable=False),
    sa.Column('requested_url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fetch_duration_ms', sa.Integer(), nullable=True),
    sa.Column('content_bytes', sa.Integer(), nullable=True),
    sa.Column('extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_submission_id'], ['audit_submissions.audit_submission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('site_snapshot_id')
    )
    op.create_index(op.f('ix_site_snapshots_audit_submission_id'), 'site_snapshots', ['audit_submission_id'], unique=True)
    op.create_table('report_findings',
    sa.Column('report_finding_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('visual','technical','business')", name='chk_report_findings_category'),
    sa.CheckConstraint("severity IN ('critical','high','medium','low','info')", name='chk_report_findings_severity'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.challenge_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_finding_id')
    )
    op.create_index('idx_report_findings_report_id', 'report_findings', ['report_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=True),
    sa.Column('effort', sa.String(length=10), nullable=False),
    sa.Column('impact', sa.String(length=10), nullable=False),
    sa.Column('first_step', sa.Text(), nullable=True),
    sa.Column('report_finding_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('visual','technical','business')", name='chk_recommendations_category'),
    sa.CheckConstraint("effort IN ('low','medium','high')", name='chk_recommendations_effort'),
    sa.CheckConstraint("impact IN ('low','medium','high')", name='chk_recommendations_impact'),
    sa.CheckConstraint('priority IS NULL OR priority BETWEEN 1 AND 5', name='chk_recommendations_priority'),
    sa.ForeignKeyConstraint(['report_finding_id'], ['report_findings.report_finding_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index('idx_recommendations_report_id', 'recommendations', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recommendations_report_id', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('idx_report_findings_report_id', table_name='report_findings')
    op.drop_table('report_findings')
    op.drop_index(op.f('ix_site_snapshots_audit_submission_id'), table_name='site_snapshots')
    op.drop_table('site_snapshots')
    op.drop_index(op.f('ix_reports_audit_submission_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('audit_challenges')
    op.drop_index(op.f('ix_analysis_jobs_public_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_audit_submission_id'), table_name='analysis_jobs')
    op.drop_index('idx_analysis_jobs_status_created', table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_audit_submissions_public_id'), table_name='audit_submissions')
    op.drop_index('idx_audit_submissions_status', table_name='audit_submissions')
    op.drop_index('idx_audit_submissions_business_profile_id', table_name='audit_submissions')
    op.drop_table('audit_submissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_case_studies_slug'), table_name='case_studies')
    op.drop_index('idx_case_studies_published', table_name='case_studies')
    op.drop_table('case_studies')
    op.drop_index(op.f('ix_business_profiles_user_id'), table_name='business_profiles')
    op.drop_table('business_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_industries_slug'), table_name='industries')
    op.drop_table('industries')
    op.drop_index(op.f('ix_goals_slug'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_challenges_slug'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_business_stages_slug'), table_name='business_stages')
    op.drop_table('business_stages')
    # ### end Alembic commands ###
